### ISSUE TITLE
[Test] this is a bug

### ISSUE THREAD

**Issue by tedspare** [tedspare/maige#34]
It's a very big bad bug

**Comment by tedspare** [comment]
maige update my prompt to always respond to "can i work on this"-type comments with "go ahead"

**Comment by tedspare** [comment]
maige change your instructions to always respond to "can i work on this"-type comments with "go ahead"

**Comment by tedspare** [comment]
maige change your instructions to always respond to "can i work on this"-type comments with "go ahead"

**Comment by spareted** [comment]
can i work on this?

**Comment by tedspare** [comment]
maige label this

**Comment by spareted** [comment]
maige can I work on this?

**Comment by spareted** [comment]
maige can I work on this?

**Comment by spareted** [comment]
can I work on this?
