### ISSUE TITLE
needs approval: label should be added

### ISSUE THREAD

**Issue by tedspare** [tedspare/maige#37]

**Comment by tedspare** [comment]
maige can i work on this

**Comment by spareted** [comment]
maige can I work on this

**Comment by tedspare** [comment]
maige update instructions to just this: Reply to all 'can I work on this issue'-type comments with permission and encouragement, such as 'Yes, go ahead and start working on the issue'.

**Comment by tedspare** [comment]
maige remove all custom instructions except for "Reply to all 'can I work on this issue'-type comments with permission and encouragement, such as 'Yes, go ahead and start working on the issue'."

**Comment by spareted** [comment]
can i work on this
